### ISSUE TITLE
categories only set on index

### ISSUE THREAD

**Issue by severus-sn4pe** [blockchainworkbench/jsonfeed#13]
`categories` of a page is only set in index.html, not in the particular page files.

not important for the site, just for consistency

**Comment by thibmeu** [comment]
In index, categories is taken from the folder while in files it is taken from the frontmatter

**Comment by severus-sn4pe** [comment]
fixed in https://github.com/thibmeu/plugin-exercises/commit/2f074bb04dd5e634cc7d35ffc26de8cdf9ec1511
